In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

## Making an array in Numpy

Make a simple array of zeros.

In [3]:
a = np.zeros(100, dtype=np.int32)
print(a)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


Check size (number of elements) and number of bytes per element.

In [21]:
print(a.size)
print(a.itemsize)

100
4


64-bit quantities of cource take more memory per element.

In [24]:
a = np.zeros(100, dtype=np.float64)
print(a.itemsize)

8


Make an array of ones, this time with a floating point data type.

In [25]:
a = np.ones(100, dtype=np.float32)
print(a)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


Make an array with an increasing sequence of numbers.

In [26]:
a = np.arange(100, dtype=np.int32)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


Reference different elements of the array.

In [27]:
print(a[0])

0


In [28]:
print(a[50])

50


Reference a range of elements. Note oddity that it is a[first:last+1].

In [29]:
print(a[2:5])

[2 3 4]


Can use shortcuts to reference to end of array.

In [30]:
print(a[90:])

[90 91 92 93 94 95 96 97 98 99]


## Multidimensional arrays

In [55]:
a = np.ones((12, 4), dtype=np.int32)

In [56]:
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [57]:
aflat = a.flatten()

In [59]:
a[2, 3] = 2
print(aflat)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1]
